# Telegram user IDs được phép dùng bot.
# Lấy user_id bằng cách nhắn @userinfobot hoặc xem log bot khi gửi message lần đầu.
users:
  - 7517515783   # Duy Luan (placeholder)
  - 183732190 #Tinh
  - 254625781 #Hien
  # - 987654321 # tên SRE khác
